<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SearchKeywordsSeeder extends Seeder
{
    public function run()
    {
        // daftar phrase (singkat untuk contoh; gunakan daftar lengkapmu)
        $phrases = ["abk",	
            "kapal",
            "tanker",
            "accenture program",
            "magang",
            "account executive",
            "account manager",
            "account payable",
            "account receivable staff",
            "accounting",
            "canggu",
            "accounting fresh graduate",
            "accounting jakarta selatan",
            "accounting job",
            "accounting manager",
            "accounting pertambangan",
            "accounting staff",
            "accounting supervisor",
            "accounting work from home",
            "bsd",
            "accounting finance",
            "accounting fresh graduated",
            "accounting gaji 15 juta",
            "accounting gaji 7 juta",
            "accounting internship",
            "accounting pt unilever indonesia",
            "accounting wfh",
            "accounting hotel",
            "actuarial",
            "aktuaria",
            "actuarial junior konsultan",
            "actuarial internship",
            "ada mess lulusan sma",
            "adira finance pt cabang",
            "admin",
            "asnaff group",
            "pt sanbe farma",
            "admin chat",
            "admin e commerce",
            "freelance",
            "admin engineering",
            "admin finance",
            "admin jakarta pusat",
            "admin media sosial",
            "admin media sosial remote",
            "admin online shop",
            "pelajar",
            "smp",
            "admin online shop remote",
            "admin online shop sambil kuliah work from home",
            "admin online kerja jarak jauh",
            "admin sales",
            "admin shopee",
            "admin smk",
            "admin sosial media part time",
            "admin whatsapp",
            "bumn bumd",
            "ciputra world",
            "freelance bales chat",
            "freelance online shop",
            "glodok",
            "gunung putri",
            "harco mangga dua",
            "indogadai",
            "j&t express",
            "j&t express taluk kuantan",
            "kantor camat",
            "kantor kelurahan",
            "kemenag",
            "koperasi",
            "museum",
            "pt dinamika daya segara",
            "pt hm sampoerna",
            "pt js corp boyolali",
            "pergudangan 99 tangrang",
            "pertambangan",
            "rs polri",
            "rumah sakit",
            "surabaya barat",
            "taman tekno bsd",
            "tu staff",
            "tu staff sekolah",
            "usia 50 tahun",
            "walk in interview",
            "wfh",
            "indogrosir",
            "jogja city mall",
            "kawasan deltamas",
            "kawasan mm2100",
            "online shop",
            "pancing",
            "pt pos indonesia",
            "rumah sakit putri hijau",
            "tambang batu bara",
            "tata usaha sekolah",
            "administrasi",
            "bandara soekarno hatta",
            "cileungsi",
            "di graha pena makassar",
            "usia 42 tahun",
            "usia 55 tahun",
            "administrasi data entry",
            "administrasi gudang",
            "administrasi gudang usia 42 tahun",
            "administrasi gudang usia 45 tahun",
            "administrasi gudang usia 47 tahun",
            "administrasi gudang usia 48 tahun",
            "administrasi gudang usia 55 tahun",
            "administrasi gudang usia 56 tahun",
            "administrasi gudang usia 58 tahun",
            "administrasi gudang usia 60",
            "administrasi jakarta selatan",
            "administrasi kesehatan",
            "administrasi lulusan sma",
            "administrasi lulusan smk",
            "administrasi negara bumn",
            "administrasi public",
            "administrasi publik bumn",
            "administrasi ringan untuk usia 50 tahun",
            "administrasi rumah sakit",
            "administrasi sekolah",
            "arsip dokumen",
            "daerah dadap kosambi",
            "kabupaten semarang",
            "kantor notaris",
            "kelapa sawit rea kaltim",
            "kim 1",
            "pt kalla group",
            "pt musim mas",
            "pt pertamina",
            "administrasi staff",
            "umur 50 tahun",
            "pt dlj karawang",
            "samsat",
            "advokat legal",
            "aeon",
            "agency advertising",
            "agroindustri manajemem teknologi pertanian",
            "agronomi agroteknologi pertanian",
            "agronomist seed pesticide fertilizer",
            "ahli gizi catering",
            "ahli gizi nutritionist nutrition",
            "ahli gizi pt pertamina",
            "ahli gizi pertambangan",
            "ahli gizi perusahaan makanan",
            "ahli gizi quality control",
            "ahli gizi rumah sakit",
            "ahli gizi tanpa str",
            "ahli gizi nutritionist",
            "ahli k3",
            "ai engineer",
            "ai intern",
            "ai training",
            "aircraft maintenance",
            "airlines",
            "ajinomoto indonesia pt mojokerto",
            "ajudan pribadi serius",
            "akuntansi bumn",
            "akuntansi magang",
            "akuntansi tanpa pengalaman",
            "akunting gaji 10 juta",
            "alam sutera",
            "alam sutera living word",
            "alam sutera part time",
            "alam sutera pasar 8",
            "alamat pt iss indonesia cleaning service",
            "alat berat",
            "all",
            "all job vacancy",
            "ambarukmo plaza",
            "aml",
            "anak tanpa ijazah tanpa ktp toko",
            "anak tanpa ijazah tanpa ktp toko lulusan smp",
            "anak tanpa ijazah toko",
            "analis kesehatan",
            "analis data rumah sakit",
            "analis kesehatan laboratorium korea",
            "analis kesehatan bumn",
            "analis kesehatan freeport",
            "analis kesehatan magang",
            "analis kesehatan mcu",
            "analis kesehatan pertambangan",
            "analis kesehatan teknologi laboratorium medik",
            "analis kimia",
            "analis kimia bumn",
            "analis kimia lab analyst lab technician",
            "analis kimia oil gas tambang",
            "analis kimia qc qa",
            "analis kimia qc qa lulusan smk",
            "analis laboratorium",
            "analis laboratorium pertambangan",
            "analis laboratorium puskesmas",
            "analis trading",
            "analis laboratorium klinik rumah sakit",
            "anchor reporter presenter",
            "angular",
            "animasi pkl smk jurusan animasi",
            "animation 3d animator remote",
            "animator animation 3d 2d illustrator",
            "antar jemput anak sekolah depok",
            "apac remote",
            "apotek k24 kurir",
            "apotek loker",
            "apotek part time",
            "apoteker",
            "apoteker siloam hospital",
            "apoteker fresh graduate",
            "apoteker bumn",
            "apoteker farmasi apotek rumah sakit industri",
            "apoteker guardian",
            "apoteker industri farmasi",
            "apoteker klinik",
            "apoteker lampung",
            "apoteker non standby",
            "apoteker pt indomarco prismatama",
            "apoteker paragon",
            "apoteker part time",
            "apoteker pbf",
            "apoteker pertambangan",
            "apoteker rs hermina",
            "apoteker rumah sakit",
            "apoteker farmasi",
            "apoteker farmasi jepang work from home",
            "apoteker klinik kecantikan",
            "apoteker puskesmas",
            "apoteker rs pertamina",
            "apoteker rsud",
            "apply job",
            "apply now",
            "appraisal bank",
            "appraisal penilai kjpp",
            "architect",
            "arsip",
            "arsip administrasi",
            "arsitek",
            "arsitek teknik lulusan smk",
            "arsitek interior 3d",
            "arsitek interior 3d fresh graduate",
            "arsitek singapore",
            "arsitektur lanskap bumn",
            "arsitektur bumn",
            "art director",
            "art seni lukis",
            "art seni lukis museum",
            "art seni lukis galeri",
            "artificial intelligence",
            "artis casting film",
            "artis casting film aktris aktor",
            "artis casting film ftv sctv",
            "artis casting film indosiar",
            "artis casting film sctv",
            "artis casting film sinetron",
            "artis casting film dewasa",
            "artis casting film figuran",
            "asisten afdeling divisi agronomi perkebunan",
            "asisten apoteker",
            "asisten apoteker apotek rumah sakit klinik",
            "asisten apoteker rumah sakit",
            "asisten apoteker tenaga teknis kefarmasian",
            "asisten apoteker klinik kecantikan",
            "asisten dosen guru",
            "asisten kebun perkebunan",
            "asisten peneliti kesehatan masyarakat",
            "asisten perawat rumah sakit",
            "asisten pribadi",
            "asisten psikolog psikologi",
            "asisten psikolog psikologi konselor",
            "asisten sortasi kelapa sawit",
            "asisten surveyor bangunan juru ukur",
            "asisten gaji 10 juta",
            "asisten gaji 20 juta",
            "asisten perawat klinik",
            "asisten perkebunan kelapa sawit",
            "asisten pribadi tante tante",
            "asisten pribadi tante tante girang",
            "asset management manajer investasi",
            "asuransi",
            "asuransi umum",
            "atlm analis kesehatan laboratorium",
            "atm",
            "audio",
            "audio editing",
            "audioman soundman sound engineer",
            "audit",
            "audit halal",
            "audit magang",
            "australia remote",
            "australia farm",
            "automation engineer",
            "avenzel hotel cibubur",
            "aviation",
            "ayana hospitality",
            "ayana resort",
            "azarine beauty advisor",
        ];

        // ambil daftar kolom yang ada di tabel search_logs
        $columns = DB::getSchemaBuilder()->getColumnListing('search_logs');

        $rows = [];
        $now = now();

        foreach ($phrases as $p) {
            $row = [];

            // selalu tambahkan kolom 'q' bila ada
            if (in_array('q', $columns)) {
                $row['q'] = $p;
            }

            // tambahkan timestamp jika ada kolomnya
            if (in_array('created_at', $columns)) {
                $row['created_at'] = $now;
            }
            if (in_array('updated_at', $columns)) {
                $row['updated_at'] = $now;
            }

            // tambahkan 'source' atau 'type' jika ada (opsional)
            if (in_array('source', $columns) && !isset($row['source'])) {
                $row['source'] = 'seeder';
            }

            // contoh: jika kolom 'ip' ada, masukkan; jika tidak, skip
            if (in_array('ip', $columns)) {
                $row['ip'] = '127.0.0.1';
            }

            if (in_array('user_agent', $columns)) {
                $row['user_agent'] = 'seeder';
            }

            // hanya push row jika tidak kosong dan punya 'q'
            if (!empty($row) && isset($row['q'])) {
                $rows[] = $row;
            }

            // insert in batches to avoid giant single insert
            if (count($rows) >= 500) {
                DB::table('search_logs')->insert($rows);
                $rows = [];
            }
        }

        if (count($rows)) {
            DB::table('search_logs')->insert($rows);
        }

        $this->command->info('SearchKeywordsSeeder: inserted ' . count($phrases) . ' rows (where q column exists).');
    }
}

